import React, { createContext, useContext, useState, useCallback } from 'react';

export type Language = 'en' | 'hi' | 'es' | 'fr' | 'de' | 'ar' | 'zh' | 'pt' | 'bn' | 'ta';

export const SUPPORTED_LANGUAGES: { code: Language; name: string; nativeName: string }[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी' },
  { code: 'es', name: 'Spanish', nativeName: 'Español' },
  { code: 'fr', name: 'French', nativeName: 'Français' },
  { code: 'de', name: 'German', nativeName: 'Deutsch' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية' },
  { code: 'zh', name: 'Chinese', nativeName: '中文' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
];

interface TranslationEntry {
  en: string;
  hi: string;
  es: string;
  fr: string;
  de: string;
  ar: string;
  zh: string;
  pt: string;
  bn: string;
  ta: string;
}

interface Translations {
  [key: string]: TranslationEntry;
}

const translations: Translations = {
  // Header & Navigation
  appTitle: {
    en: 'Medical Assistant',
    hi: 'चिकित्सा सहायक',
    es: 'Asistente Médico',
    fr: 'Assistant Médical',
    de: 'Medizinischer Assistent',
    ar: 'المساعد الطبي',
    zh: '医疗助手',
    pt: 'Assistente Médico',
    bn: 'চিকিৎসা সহায়ক',
    ta: 'மருத்துவ உதவியாளர்',
  },
  disclaimer: {
    en: 'For informational purposes only. Always consult a healthcare professional.',
    hi: 'केवल जानकारी के लिए। हमेशा स्वास्थ्य पेशेवर से परामर्श करें।',
    es: 'Solo con fines informativos. Siempre consulte a un profesional de la salud.',
    fr: 'À titre informatif uniquement. Consultez toujours un professionnel de santé.',
    de: 'Nur zu Informationszwecken. Konsultieren Sie immer einen Arzt.',
    ar: 'لأغراض إعلامية فقط. استشر دائمًا أخصائي الرعاية الصحية.',
    zh: '仅供参考。请务必咨询医疗专业人员。',
    pt: 'Apenas para fins informativos. Sempre consulte um profissional de saúde.',
    bn: 'শুধুমাত্র তথ্যের জন্য। সর্বদা একজন স্বাস্থ্য পেশাদারের সাথে পরামর্শ করুন।',
    ta: 'தகவல் நோக்கங்களுக்கு மட்டுமே. எப்போதும் சுகாதார நிபுணரை அணுகவும்.',
  },
  // Sidebar
  quickTopics: {
    en: 'Quick Topics',
    hi: 'त्वरित विषय',
    es: 'Temas Rápidos',
    fr: 'Sujets Rapides',
    de: 'Schnelle Themen',
    ar: 'مواضيع سريعة',
    zh: '快速主题',
    pt: 'Tópicos Rápidos',
    bn: 'দ্রুত বিষয়',
    ta: 'விரைவு தலைப்புகள்',
  },
  symptoms: {
    en: 'Symptoms',
    hi: 'लक्षण',
    es: 'Síntomas',
    fr: 'Symptômes',
    de: 'Symptome',
    ar: 'الأعراض',
    zh: '症状',
    pt: 'Sintomas',
    bn: 'লক্ষণ',
    ta: 'அறிகுறிகள்',
  },
  prevention: {
    en: 'Prevention',
    hi: 'रोकथाम',
    es: 'Prevención',
    fr: 'Prévention',
    de: 'Prävention',
    ar: 'الوقاية',
    zh: '预防',
    pt: 'Prevenção',
    bn: 'প্রতিরোধ',
    ta: 'தடுப்பு',
  },
  firstAid: {
    en: 'First Aid',
    hi: 'प्राथमिक चिकित्सा',
    es: 'Primeros Auxilios',
    fr: 'Premiers Secours',
    de: 'Erste Hilfe',
    ar: 'الإسعافات الأولية',
    zh: '急救',
    pt: 'Primeiros Socorros',
    bn: 'প্রাথমিক চিকিৎসা',
    ta: 'முதலுதவி',
  },
  whenToSeeDoctor: {
    en: 'When to See Doctor',
    hi: 'डॉक्टर को कब दिखाएं',
    es: 'Cuándo Ver al Doctor',
    fr: 'Quand Consulter un Médecin',
    de: 'Wann zum Arzt',
    ar: 'متى تزور الطبيب',
    zh: '何时看医生',
    pt: 'Quando Consultar o Médico',
    bn: 'কখন ডাক্তার দেখাবেন',
    ta: 'மருத்துவரை எப்போது பார்க்க வேண்டும்',
  },
  commonConditions: {
    en: 'Common Conditions',
    hi: 'सामान्य स्थितियाँ',
    es: 'Condiciones Comunes',
    fr: 'Conditions Courantes',
    de: 'Häufige Erkrankungen',
    ar: 'الحالات الشائعة',
    zh: '常见病症',
    pt: 'Condições Comuns',
    bn: 'সাধারণ অবস্থা',
    ta: 'பொதுவான நிலைகள்',
  },
  fever: {
    en: 'Fever',
    hi: 'बुखार',
    es: 'Fiebre',
    fr: 'Fièvre',
    de: 'Fieber',
    ar: 'الحمى',
    zh: '发烧',
    pt: 'Febre',
    bn: 'জ্বর',
    ta: 'காய்ச்சல்',
  },
  headache: {
    en: 'Headache',
    hi: 'सिरदर्द',
    es: 'Dolor de Cabeza',
    fr: 'Mal de Tête',
    de: 'Kopfschmerzen',
    ar: 'صداع',
    zh: '头痛',
    pt: 'Dor de Cabeça',
    bn: 'মাথাব্যথা',
    ta: 'தலைவலி',
  },
  cough: {
    en: 'Cough & Cold',
    hi: 'खांसी और जुकाम',
    es: 'Tos y Resfriado',
    fr: 'Toux et Rhume',
    de: 'Husten & Erkältung',
    ar: 'السعال والبرد',
    zh: '咳嗽和感冒',
    pt: 'Tosse e Resfriado',
    bn: 'কাশি এবং সর্দি',
    ta: 'இருமல் & சளி',
  },
  diabetes: {
    en: 'Diabetes',
    hi: 'मधुमेह',
    es: 'Diabetes',
    fr: 'Diabète',
    de: 'Diabetes',
    ar: 'السكري',
    zh: '糖尿病',
    pt: 'Diabetes',
    bn: 'ডায়াবেটিস',
    ta: 'நீரிழிவு',
  },
  dengue: {
    en: 'Dengue',
    hi: 'डेंगू',
    es: 'Dengue',
    fr: 'Dengue',
    de: 'Dengue',
    ar: 'حمى الضنك',
    zh: '登革热',
    pt: 'Dengue',
    bn: 'ডেঙ্গু',
    ta: 'டெங்கு',
  },
  // Chat
  placeholder: {
    en: 'Ask about symptoms, conditions, or first aid...',
    hi: 'लक्षण, स्थितियों, या प्राथमिक चिकित्सा के बारे में पूछें...',
    es: 'Pregunte sobre síntomas, condiciones o primeros auxilios...',
    fr: 'Posez des questions sur les symptômes, conditions ou premiers secours...',
    de: 'Fragen Sie nach Symptomen, Erkrankungen oder Erste Hilfe...',
    ar: 'اسأل عن الأعراض أو الحالات أو الإسعافات الأولية...',
    zh: '询问症状、疾病或急救...',
    pt: 'Pergunte sobre sintomas, condições ou primeiros socorros...',
    bn: 'লক্ষণ, অবস্থা বা প্রাথমিক চিকিৎসা সম্পর্কে জিজ্ঞাসা করুন...',
    ta: 'அறிகுறிகள், நிலைகள் அல்லது முதலுதவி பற்றி கேளுங்கள்...',
  },
  send: {
    en: 'Send',
    hi: 'भेजें',
    es: 'Enviar',
    fr: 'Envoyer',
    de: 'Senden',
    ar: 'إرسال',
    zh: '发送',
    pt: 'Enviar',
    bn: 'পাঠান',
    ta: 'அனுப்பு',
  },
  typing: {
    en: 'Typing...',
    hi: 'टाइप कर रहा है...',
    es: 'Escribiendo...',
    fr: 'En train d\'écrire...',
    de: 'Schreibt...',
    ar: 'يكتب...',
    zh: '正在输入...',
    pt: 'Digitando...',
    bn: 'টাইপ করছে...',
    ta: 'தட்டச்சு செய்கிறது...',
  },
  welcomeTitle: {
    en: 'Welcome to Medical Assistant',
    hi: 'चिकित्सा सहायक में आपका स्वागत है',
    es: 'Bienvenido al Asistente Médico',
    fr: 'Bienvenue chez l\'Assistant Médical',
    de: 'Willkommen beim Medizinischen Assistenten',
    ar: 'مرحبًا بك في المساعد الطبي',
    zh: '欢迎使用医疗助手',
    pt: 'Bem-vindo ao Assistente Médico',
    bn: 'চিকিৎসা সহায়কে স্বাগতম',
    ta: 'மருத்துவ உதவியாளருக்கு வரவேற்கிறோம்',
  },
  welcomeMessage: {
    en: 'I can help you with general health information, symptoms, prevention tips, and first aid guidance. Remember, I provide information only - always consult a doctor for proper diagnosis.',
    hi: 'मैं आपको सामान्य स्वास्थ्य जानकारी, लक्षण, रोकथाम युक्तियाँ और प्राथमिक चिकित्सा मार्गदर्शन में मदद कर सकता हूं। याद रखें, मैं केवल जानकारी प्रदान करता हूं - उचित निदान के लिए हमेशा डॉक्टर से परामर्श करें।',
    es: 'Puedo ayudarte con información general de salud, síntomas, consejos de prevención y guía de primeros auxilios. Recuerda, solo proporciono información - siempre consulta a un médico para un diagnóstico adecuado.',
    fr: 'Je peux vous aider avec des informations générales sur la santé, les symptômes, les conseils de prévention et les premiers secours. N\'oubliez pas, je fournis uniquement des informations - consultez toujours un médecin pour un diagnostic approprié.',
    de: 'Ich kann Ihnen bei allgemeinen Gesundheitsinformationen, Symptomen, Präventionstipps und Erste-Hilfe-Anleitungen helfen. Denken Sie daran, ich gebe nur Informationen - konsultieren Sie immer einen Arzt für eine richtige Diagnose.',
    ar: 'يمكنني مساعدتك بمعلومات صحية عامة، أعراض، نصائح وقائية، وإرشادات إسعافات أولية. تذكر، أقدم معلومات فقط - استشر طبيبًا دائمًا للتشخيص الصحيح.',
    zh: '我可以帮助您获取一般健康信息、症状、预防建议和急救指导。请记住，我只提供信息 - 请务必咨询医生以获得正确诊断。',
    pt: 'Posso ajudá-lo com informações gerais de saúde, sintomas, dicas de prevenção e orientação de primeiros socorros. Lembre-se, eu forneço apenas informações - sempre consulte um médico para diagnóstico adequado.',
    bn: 'আমি আপনাকে সাধারণ স্বাস্থ্য তথ্য, লক্ষণ, প্রতিরোধ টিপস এবং প্রাথমিক চিকিৎসা নির্দেশনায় সাহায্য করতে পারি। মনে রাখবেন, আমি শুধু তথ্য প্রদান করি - সঠিক রোগ নির্ণয়ের জন্য সর্বদা একজন ডাক্তারের সাথে পরামর্শ করুন।',
    ta: 'பொது சுகாதார தகவல், அறிகுறிகள், தடுப்பு குறிப்புகள் மற்றும் முதலுதவி வழிகாட்டுதலில் நான் உங்களுக்கு உதவ முடியும். நினைவில் கொள்ளுங்கள், நான் தகவல் மட்டுமே வழங்குகிறேன் - சரியான நோயறிதலுக்கு எப்போதும் மருத்துவரை அணுகவும்.',
  },
  exampleQuestions: {
    en: 'Example questions:',
    hi: 'उदाहरण प्रश्न:',
    es: 'Preguntas de ejemplo:',
    fr: 'Questions exemples:',
    de: 'Beispielfragen:',
    ar: 'أسئلة نموذجية:',
    zh: '示例问题：',
    pt: 'Perguntas de exemplo:',
    bn: 'উদাহরণ প্রশ্ন:',
    ta: 'எடுத்துக்காட்டு கேள்விகள்:',
  },
  example1: {
    en: 'What are the symptoms of dengue?',
    hi: 'डेंगू के लक्षण क्या हैं?',
    es: '¿Cuáles son los síntomas del dengue?',
    fr: 'Quels sont les symptômes de la dengue?',
    de: 'Was sind die Symptome von Dengue?',
    ar: 'ما هي أعراض حمى الضنك؟',
    zh: '登革热的症状是什么？',
    pt: 'Quais são os sintomas da dengue?',
    bn: 'ডেঙ্গুর লক্ষণ কী?',
    ta: 'டெங்குவின் அறிகுறிகள் என்ன?',
  },
  example2: {
    en: 'How can I prevent diabetes?',
    hi: 'मैं मधुमेह को कैसे रोक सकता हूं?',
    es: '¿Cómo puedo prevenir la diabetes?',
    fr: 'Comment puis-je prévenir le diabète?',
    de: 'Wie kann ich Diabetes vorbeugen?',
    ar: 'كيف يمكنني الوقاية من السكري؟',
    zh: '我如何预防糖尿病？',
    pt: 'Como posso prevenir a diabetes?',
    bn: 'আমি কীভাবে ডায়াবেটিস প্রতিরোধ করতে পারি?',
    ta: 'நீரிழிவை எப்படி தடுக்கலாம்?',
  },
  example3: {
    en: 'What should I do for a mild fever?',
    hi: 'हल्के बुखार के लिए मुझे क्या करना चाहिए?',
    es: '¿Qué debo hacer para una fiebre leve?',
    fr: 'Que dois-je faire pour une légère fièvre?',
    de: 'Was soll ich bei leichtem Fieber tun?',
    ar: 'ماذا يجب أن أفعل للحمى الخفيفة؟',
    zh: '轻微发烧应该怎么办？',
    pt: 'O que devo fazer para uma febre leve?',
    bn: 'হালকা জ্বরের জন্য আমার কী করা উচিত?',
    ta: 'லேசான காய்ச்சலுக்கு நான் என்ன செய்ய வேண்டும்?',
  },
  // Emergency
  emergencyTitle: {
    en: '🚨 EMERGENCY DETECTED',
    hi: '🚨 आपातकालीन स्थिति',
    es: '🚨 EMERGENCIA DETECTADA',
    fr: '🚨 URGENCE DÉTECTÉE',
    de: '🚨 NOTFALL ERKANNT',
    ar: '🚨 تم اكتشاف حالة طوارئ',
    zh: '🚨 检测到紧急情况',
    pt: '🚨 EMERGÊNCIA DETECTADA',
    bn: '🚨 জরুরি অবস্থা সনাক্ত',
    ta: '🚨 அவசரநிலை கண்டறியப்பட்டது',
  },
  emergencyMessage: {
    en: 'This may be a medical emergency. Please call emergency services immediately!',
    hi: 'यह एक चिकित्सा आपातकाल हो सकता है। कृपया तुरंत आपातकालीन सेवाओं को कॉल करें!',
    es: 'Esto puede ser una emergencia médica. ¡Por favor llame a los servicios de emergencia inmediatamente!',
    fr: 'Cela peut être une urgence médicale. Veuillez appeler les services d\'urgence immédiatement!',
    de: 'Dies könnte ein medizinischer Notfall sein. Bitte rufen Sie sofort den Notdienst an!',
    ar: 'قد تكون هذه حالة طوارئ طبية. يرجى الاتصال بخدمات الطوارئ فورًا!',
    zh: '这可能是医疗紧急情况。请立即拨打急救电话！',
    pt: 'Isso pode ser uma emergência médica. Por favor, ligue para os serviços de emergência imediatamente!',
    bn: 'এটি একটি চিকিৎসা জরুরি অবস্থা হতে পারে। অনুগ্রহ করে অবিলম্বে জরুরি সেবায় কল করুন!',
    ta: 'இது மருத்துவ அவசரநிலையாக இருக்கலாம். உடனடியாக அவசர சேவைகளை அழைக்கவும்!',
  },
  emergencyNumbers: {
    en: 'Emergency Numbers (India): 112 | 102 | 108',
    hi: 'आपातकालीन नंबर (भारत): 112 | 102 | 108',
    es: 'Números de Emergencia (India): 112 | 102 | 108',
    fr: 'Numéros d\'Urgence (Inde): 112 | 102 | 108',
    de: 'Notrufnummern (Indien): 112 | 102 | 108',
    ar: 'أرقام الطوارئ (الهند): 112 | 102 | 108',
    zh: '紧急电话（印度）：112 | 102 | 108',
    pt: 'Números de Emergência (Índia): 112 | 102 | 108',
    bn: 'জরুরি নম্বর (ভারত): 112 | 102 | 108',
    ta: 'அவசர எண்கள் (இந்தியா): 112 | 102 | 108',
  },
  // Reminder
  consultDoctor: {
    en: '📋 Please consult a healthcare professional for proper diagnosis and treatment.',
    hi: '📋 कृपया उचित निदान और उपचार के लिए स्वास्थ्य पेशेवर से परामर्श करें।',
    es: '📋 Por favor consulte a un profesional de la salud para diagnóstico y tratamiento adecuados.',
    fr: '📋 Veuillez consulter un professionnel de santé pour un diagnostic et un traitement appropriés.',
    de: '📋 Bitte konsultieren Sie einen Arzt für eine richtige Diagnose und Behandlung.',
    ar: '📋 يرجى استشارة أخصائي الرعاية الصحية للتشخيص والعلاج المناسب.',
    zh: '📋 请咨询医疗专业人员以获得正确的诊断和治疗。',
    pt: '📋 Por favor, consulte um profissional de saúde para diagnóstico e tratamento adequados.',
    bn: '📋 সঠিক রোগ নির্ণয় এবং চিকিৎসার জন্য অনুগ্রহ করে একজন স্বাস্থ্য পেশাদারের সাথে পরামর্শ করুন।',
    ta: '📋 சரியான நோயறிதல் மற்றும் சிகிச்சைக்கு சுகாதார நிபுணரை அணுகவும்.',
  },
  getCheckup: {
    en: '🏥 GET A CHECK-UP',
    hi: '🏥 जांच करवाएं',
    es: '🏥 HÁGASE UN CHEQUEO',
    fr: '🏥 FAITES UN BILAN DE SANTÉ',
    de: '🏥 LASSEN SIE SICH UNTERSUCHEN',
    ar: '🏥 احصل على فحص طبي',
    zh: '🏥 进行检查',
    pt: '🏥 FAÇA UM CHECK-UP',
    bn: '🏥 চেক-আপ করান',
    ta: '🏥 பரிசோதனை செய்யுங்கள்',
  },
  checkupReminder: {
    en: 'This information is not a substitute for professional medical advice. Schedule a check-up with your doctor.',
    hi: 'यह जानकारी पेशेवर चिकित्सा सलाह का विकल्प नहीं है। अपने डॉक्टर के साथ जांच का समय निर्धारित करें।',
    es: 'Esta información no sustituye el consejo médico profesional. Programe una cita con su médico.',
    fr: 'Cette information ne remplace pas un avis médical professionnel. Prenez rendez-vous avec votre médecin.',
    de: 'Diese Informationen ersetzen keine professionelle medizinische Beratung. Vereinbaren Sie einen Termin mit Ihrem Arzt.',
    ar: 'هذه المعلومات ليست بديلاً عن المشورة الطبية المهنية. حدد موعدًا لفحص مع طبيبك.',
    zh: '此信息不能替代专业医疗建议。请与您的医生预约检查。',
    pt: 'Esta informação não substitui o aconselhamento médico profissional. Agende uma consulta com seu médico.',
    bn: 'এই তথ্য পেশাদার চিকিৎসা পরামর্শের বিকল্প নয়। আপনার ডাক্তারের সাথে চেক-আপের সময় নির্ধারণ করুন।',
    ta: 'இந்த தகவல் தொழில்முறை மருத்துவ ஆலோசனைக்கு மாற்றாக இல்லை. உங்கள் மருத்துவரிடம் பரிசோதனை நேரம் திட்டமிடுங்கள்.',
  },
  // Language
  language: {
    en: 'Language',
    hi: 'भाषा',
    es: 'Idioma',
    fr: 'Langue',
    de: 'Sprache',
    ar: 'اللغة',
    zh: '语言',
    pt: 'Idioma',
    bn: 'ভাষা',
    ta: 'மொழி',
  },
  selectLanguage: {
    en: 'Select Language',
    hi: 'भाषा चुनें',
    es: 'Seleccionar Idioma',
    fr: 'Sélectionner la Langue',
    de: 'Sprache Auswählen',
    ar: 'اختر اللغة',
    zh: '选择语言',
    pt: 'Selecionar Idioma',
    bn: 'ভাষা নির্বাচন করুন',
    ta: 'மொழியைத் தேர்ந்தெடுக்கவும்',
  },
  // Voice Input
  voiceStart: {
    en: 'Start voice input',
    hi: 'वॉयस इनपुट शुरू करें',
    es: 'Iniciar entrada de voz',
    fr: 'Démarrer la saisie vocale',
    de: 'Spracheingabe starten',
    ar: 'بدء الإدخال الصوتي',
    zh: '开始语音输入',
    pt: 'Iniciar entrada de voz',
    bn: 'ভয়েস ইনপুট শুরু করুন',
    ta: 'குரல் உள்ளீட்டைத் தொடங்கு',
  },
  voiceStop: {
    en: 'Stop voice input',
    hi: 'वॉयस इनपुट बंद करें',
    es: 'Detener entrada de voz',
    fr: 'Arrêter la saisie vocale',
    de: 'Spracheingabe stoppen',
    ar: 'إيقاف الإدخال الصوتي',
    zh: '停止语音输入',
    pt: 'Parar entrada de voz',
    bn: 'ভয়েস ইনপুট বন্ধ করুন',
    ta: 'குரல் உள்ளீட்டை நிறுத்து',
  },
  voiceListening: {
    en: 'Listening... Speak now',
    hi: 'सुन रहा है... अब बोलें',
    es: 'Escuchando... Habla ahora',
    fr: 'Écoute... Parlez maintenant',
    de: 'Hört zu... Sprechen Sie jetzt',
    ar: 'يستمع... تحدث الآن',
    zh: '正在聆听...请说话',
    pt: 'Ouvindo... Fale agora',
    bn: 'শুনছি... এখন বলুন',
    ta: 'கேட்கிறது... இப்போது பேசுங்கள்',
  },
  voiceError: {
    en: 'Voice recognition error. Please try again.',
    hi: 'वॉयस पहचान में त्रुटि। कृपया पुनः प्रयास करें।',
    es: 'Error de reconocimiento de voz. Inténtalo de nuevo.',
    fr: 'Erreur de reconnaissance vocale. Veuillez réessayer.',
    de: 'Spracherkennungsfehler. Bitte versuchen Sie es erneut.',
    ar: 'خطأ في التعرف على الصوت. حاول مرة أخرى.',
    zh: '语音识别错误。请重试。',
    pt: 'Erro de reconhecimento de voz. Tente novamente.',
    bn: 'ভয়েস সনাক্তকরণে ত্রুটি। অনুগ্রহ করে আবার চেষ্টা করুন।',
    ta: 'குரல் அடையாள பிழை. மீண்டும் முயற்சிக்கவும்.',
  },
  voiceNotSupported: {
    en: 'Voice input is not supported in your browser.',
    hi: 'आपके ब्राउज़र में वॉयस इनपुट समर्थित नहीं है।',
    es: 'La entrada de voz no es compatible con tu navegador.',
    fr: 'La saisie vocale n\'est pas prise en charge par votre navigateur.',
    de: 'Spracheingabe wird in Ihrem Browser nicht unterstützt.',
    ar: 'الإدخال الصوتي غير مدعوم في متصفحك.',
    zh: '您的浏览器不支持语音输入。',
    pt: 'A entrada de voz não é suportada no seu navegador.',
    bn: 'আপনার ব্রাউজারে ভয়েস ইনপুট সমর্থিত নয়।',
    ta: 'உங்கள் உலாவியில் குரல் உள்ளீடு ஆதரிக்கப்படவில்லை.',
  },
  // Theme
  theme: {
    en: 'Theme',
    hi: 'थीम',
    es: 'Tema',
    fr: 'Thème',
    de: 'Thema',
    ar: 'السمة',
    zh: '主题',
    pt: 'Tema',
    bn: 'থিম',
    ta: 'தீம்',
  },
  lightMode: {
    en: 'Light Mode',
    hi: 'लाइट मोड',
    es: 'Modo Claro',
    fr: 'Mode Clair',
    de: 'Heller Modus',
    ar: 'الوضع الفاتح',
    zh: '浅色模式',
    pt: 'Modo Claro',
    bn: 'লাইট মোড',
    ta: 'லைட் மோட்',
  },
  darkMode: {
    en: 'Dark Mode',
    hi: 'डार्क मोड',
    es: 'Modo Oscuro',
    fr: 'Mode Sombre',
    de: 'Dunkler Modus',
    ar: 'الوضع الداكن',
    zh: '深色模式',
    pt: 'Modo Escuro',
    bn: 'ডার্ক মোড',
    ta: 'டார்க் மோட்',
  },
  eyeComfortMode: {
    en: 'Eye Comfort',
    hi: 'आई कम्फर्ट',
    es: 'Confort Visual',
    fr: 'Confort Visuel',
    de: 'Augenschonend',
    ar: 'راحة العين',
    zh: '护眼模式',
    pt: 'Conforto Visual',
    bn: 'আই কমফোর্ট',
    ta: 'கண் ஆறுதல்',
  },
  // Tutorial
  tutorialWelcomeTitle: {
    en: 'Welcome!',
    hi: 'स्वागत है!',
    es: '¡Bienvenido!',
    fr: 'Bienvenue!',
    de: 'Willkommen!',
    ar: 'مرحباً!',
    zh: '欢迎！',
    pt: 'Bem-vindo!',
    bn: 'স্বাগতম!',
    ta: 'வரவேற்கிறோம்!',
  },
  tutorialWelcomeDesc: {
    en: 'This is your Medical Assistant. Let me guide you through the features to help you get the most out of this tool.',
    hi: 'यह आपका चिकित्सा सहायक है। मुझे आपको सुविधाओं के बारे में बताने दें ताकि आप इस उपकरण का अधिकतम लाभ उठा सकें।',
    es: 'Este es tu Asistente Médico. Déjame guiarte a través de las funciones para ayudarte a aprovechar al máximo esta herramienta.',
    fr: 'Ceci est votre Assistant Médical. Laissez-moi vous guider à travers les fonctionnalités pour vous aider à tirer le meilleur parti de cet outil.',
    de: 'Dies ist Ihr Medizinischer Assistent. Lassen Sie mich Sie durch die Funktionen führen, um das Beste aus diesem Tool herauszuholen.',
    ar: 'هذا هو مساعدك الطبي. دعني أرشدك عبر الميزات لمساعدتك في الاستفادة القصوى من هذه الأداة.',
    zh: '这是您的医疗助手。让我带您了解各项功能，帮助您充分利用此工具。',
    pt: 'Este é o seu Assistente Médico. Deixe-me guiá-lo através das funcionalidades para ajudá-lo a tirar o máximo proveito desta ferramenta.',
    bn: 'এটি আপনার চিকিৎসা সহায়ক। আমাকে আপনাকে বৈশিষ্ট্যগুলি সম্পর্কে গাইড করতে দিন যাতে আপনি এই সরঞ্জামটি সর্বাধিক ব্যবহার করতে পারেন।',
    ta: 'இது உங்கள் மருத்துவ உதவியாளர். இந்த கருவியை சிறப்பாக பயன்படுத்த உதவும் அம்சங்களை நான் உங்களுக்கு வழிகாட்டுகிறேன்.',
  },
  tutorialLanguageTitle: {
    en: 'Language Selection',
    hi: 'भाषा चयन',
    es: 'Selección de Idioma',
    fr: 'Sélection de Langue',
    de: 'Sprachauswahl',
    ar: 'اختيار اللغة',
    zh: '语言选择',
    pt: 'Seleção de Idioma',
    bn: 'ভাষা নির্বাচন',
    ta: 'மொழி தேர்வு',
  },
  tutorialLanguageDesc: {
    en: 'Choose your preferred language. The entire interface, including AI responses and voice recognition, will adapt to your choice.',
    hi: 'अपनी पसंदीदा भाषा चुनें। पूरा इंटरफ़ेस, AI प्रतिक्रियाओं और वॉयस रिकग्निशन सहित, आपकी पसंद के अनुसार बदल जाएगा।',
    es: 'Elige tu idioma preferido. Toda la interfaz, incluidas las respuestas de IA y el reconocimiento de voz, se adaptará a tu elección.',
    fr: 'Choisissez votre langue préférée. L\'ensemble de l\'interface, y compris les réponses IA et la reconnaissance vocale, s\'adaptera à votre choix.',
    de: 'Wählen Sie Ihre bevorzugte Sprache. Die gesamte Oberfläche, einschließlich KI-Antworten und Spracherkennung, passt sich Ihrer Wahl an.',
    ar: 'اختر لغتك المفضلة. ستتكيف الواجهة بأكملها، بما في ذلك ردود الذكاء الاصطناعي والتعرف على الصوت، مع اختيارك.',
    zh: '选择您偏好的语言。整个界面，包括AI回复和语音识别，都会适应您的选择。',
    pt: 'Escolha seu idioma preferido. Toda a interface, incluindo respostas de IA e reconhecimento de voz, se adaptará à sua escolha.',
    bn: 'আপনার পছন্দের ভাষা নির্বাচন করুন। AI প্রতিক্রিয়া এবং ভয়েস রিকগনিশন সহ সম্পূর্ণ ইন্টারফেস আপনার পছন্দের সাথে মানিয়ে নেবে।',
    ta: 'உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும். AI பதில்கள் மற்றும் குரல் அடையாளம் உட்பட முழு இடைமுகமும் உங்கள் தேர்வுக்கு ஏற்ப மாறும்.',
  },
  tutorialLanguageHint: {
    en: 'Click to change the language',
    hi: 'भाषा बदलने के लिए क्लिक करें',
    es: 'Haz clic para cambiar el idioma',
    fr: 'Cliquez pour changer la langue',
    de: 'Klicken Sie, um die Sprache zu ändern',
    ar: 'انقر لتغيير اللغة',
    zh: '点击更改语言',
    pt: 'Clique para mudar o idioma',
    bn: 'ভাষা পরিবর্তন করতে ক্লিক করুন',
    ta: 'மொழியை மாற்ற கிளிக் செய்யவும்',
  },
  tutorialThemeTitle: {
    en: 'Theme Settings',
    hi: 'थीम सेटिंग्स',
    es: 'Configuración de Tema',
    fr: 'Paramètres de Thème',
    de: 'Theme-Einstellungen',
    ar: 'إعدادات السمة',
    zh: '主题设置',
    pt: 'Configurações de Tema',
    bn: 'থিম সেটিংস',
    ta: 'தீம் அமைப்புகள்',
  },
  tutorialThemeDesc: {
    en: 'Switch between Light, Dark, or Eye Comfort mode. Eye Comfort uses warm colors to reduce eye strain during extended use.',
    hi: 'लाइट, डार्क, या आई कम्फर्ट मोड के बीच स्विच करें। आई कम्फर्ट लंबे समय तक उपयोग के दौरान आंखों की थकान को कम करने के लिए गर्म रंगों का उपयोग करता है।',
    es: 'Cambia entre el modo Claro, Oscuro o Confort Visual. El Confort Visual usa colores cálidos para reducir la fatiga ocular durante el uso prolongado.',
    fr: 'Basculez entre le mode Clair, Sombre ou Confort Visuel. Le Confort Visuel utilise des couleurs chaudes pour réduire la fatigue oculaire lors d\'une utilisation prolongée.',
    de: 'Wechseln Sie zwischen Hell, Dunkel oder Augenschonend. Augenschonend verwendet warme Farben, um die Augenbelastung bei längerer Nutzung zu reduzieren.',
    ar: 'التبديل بين الوضع الفاتح أو الداكن أو راحة العين. راحة العين تستخدم ألواناً دافئة لتقليل إجهاد العين أثناء الاستخدام المطول.',
    zh: '在浅色、深色或护眼模式之间切换。护眼模式使用暖色调来减少长时间使用时的眼睛疲劳。',
    pt: 'Alterne entre o modo Claro, Escuro ou Conforto Visual. O Conforto Visual usa cores quentes para reduzir o cansaço visual durante o uso prolongado.',
    bn: 'লাইট, ডার্ক বা আই কমফোর্ট মোডের মধ্যে স্যুইচ করুন। আই কমফোর্ট দীর্ঘ ব্যবহারের সময় চোখের চাপ কমাতে উষ্ণ রং ব্যবহার করে।',
    ta: 'லைட், டார்க் அல்லது கண் ஆறுதல் பயன்முறைக்கு மாறவும். கண் ஆறுதல் நீண்ட நேர பயன்பாட்டின் போது கண் அழுத்தத்தைக் குறைக்க சூடான வண்ணங்களைப் பயன்படுத்துகிறது.',
  },
  tutorialThemeHint: {
    en: 'Try switching themes!',
    hi: 'थीम बदलकर देखें!',
    es: '¡Prueba a cambiar los temas!',
    fr: 'Essayez de changer de thème!',
    de: 'Versuchen Sie, das Theme zu wechseln!',
    ar: 'جرب تبديل السمات!',
    zh: '尝试切换主题！',
    pt: 'Tente mudar os temas!',
    bn: 'থিম পরিবর্তন করে দেখুন!',
    ta: 'தீம்களை மாற்றி பாருங்கள்!',
  },
  tutorialQuickTopicsTitle: {
    en: 'Quick Topics',
    hi: 'त्वरित विषय',
    es: 'Temas Rápidos',
    fr: 'Sujets Rapides',
    de: 'Schnelle Themen',
    ar: 'مواضيع سريعة',
    zh: '快速主题',
    pt: 'Tópicos Rápidos',
    bn: 'দ্রুত বিষয়',
    ta: 'விரைவு தலைப்புகள்',
  },
  tutorialQuickTopicsDesc: {
    en: 'Access common health topics instantly. Click any topic to start a conversation about symptoms, prevention, first aid, or when to see a doctor.',
    hi: 'सामान्य स्वास्थ्य विषयों तक तुरंत पहुंचें। लक्षण, रोकथाम, प्राथमिक चिकित्सा, या डॉक्टर से कब मिलें के बारे में बातचीत शुरू करने के लिए किसी भी विषय पर क्लिक करें।',
    es: 'Accede a temas de salud comunes al instante. Haz clic en cualquier tema para iniciar una conversación sobre síntomas, prevención, primeros auxilios o cuándo ver al médico.',
    fr: 'Accédez instantanément aux sujets de santé courants. Cliquez sur n\'importe quel sujet pour démarrer une conversation sur les symptômes, la prévention, les premiers secours ou quand consulter un médecin.',
    de: 'Greifen Sie sofort auf häufige Gesundheitsthemen zu. Klicken Sie auf ein Thema, um ein Gespräch über Symptome, Prävention, Erste Hilfe oder wann Sie einen Arzt aufsuchen sollten zu beginnen.',
    ar: 'الوصول الفوري إلى المواضيع الصحية الشائعة. انقر على أي موضوع لبدء محادثة حول الأعراض أو الوقاية أو الإسعافات الأولية أو متى تزور الطبيب.',
    zh: '即时访问常见健康主题。点击任何主题开始关于症状、预防、急救或何时看医生的对话。',
    pt: 'Acesse tópicos de saúde comuns instantaneamente. Clique em qualquer tópico para iniciar uma conversa sobre sintomas, prevenção, primeiros socorros ou quando consultar o médico.',
    bn: 'সাধারণ স্বাস্থ্য বিষয়গুলিতে তাৎক্ষণিক অ্যাক্সেস পান। লক্ষণ, প্রতিরোধ, প্রাথমিক চিকিৎসা, বা কখন ডাক্তার দেখাবেন সে বিষয়ে কথোপকথন শুরু করতে যেকোনো বিষয়ে ক্লিক করুন।',
    ta: 'பொதுவான சுகாதார தலைப்புகளை உடனடியாக அணுகவும். அறிகுறிகள், தடுப்பு, முதலுதவி அல்லது மருத்துவரை எப்போது பார்க்க வேண்டும் என்பது பற்றிய உரையாடலைத் தொடங்க எந்த தலைப்பையும் கிளிக் செய்யவும்.',
  },
  tutorialQuickTopicsHint: {
    en: 'Click a topic to ask about it',
    hi: 'इसके बारे में पूछने के लिए किसी विषय पर क्लिक करें',
    es: 'Haz clic en un tema para preguntar sobre él',
    fr: 'Cliquez sur un sujet pour poser des questions',
    de: 'Klicken Sie auf ein Thema, um danach zu fragen',
    ar: 'انقر على موضوع للسؤال عنه',
    zh: '点击主题来询问',
    pt: 'Clique em um tópico para perguntar sobre ele',
    bn: 'এটি সম্পর্কে জিজ্ঞাসা করতে একটি বিষয়ে ক্লিক করুন',
    ta: 'அதைப் பற்றி கேட்க ஒரு தலைப்பைக் கிளிக் செய்யவும்',
  },
  tutorialConditionsTitle: {
    en: 'Common Conditions',
    hi: 'सामान्य स्थितियाँ',
    es: 'Condiciones Comunes',
    fr: 'Conditions Courantes',
    de: 'Häufige Erkrankungen',
    ar: 'الحالات الشائعة',
    zh: '常见病症',
    pt: 'Condições Comuns',
    bn: 'সাধারণ অবস্থা',
    ta: 'பொதுவான நிலைகள்',
  },
  tutorialConditionsDesc: {
    en: 'Quick access to information about fever, headache, cough, diabetes, and dengue. These are the most commonly asked health topics.',
    hi: 'बुखार, सिरदर्द, खांसी, मधुमेह और डेंगू के बारे में जानकारी तक त्वरित पहुंच। ये सबसे अधिक पूछे जाने वाले स्वास्थ्य विषय हैं।',
    es: 'Acceso rápido a información sobre fiebre, dolor de cabeza, tos, diabetes y dengue. Estos son los temas de salud más consultados.',
    fr: 'Accès rapide aux informations sur la fièvre, les maux de tête, la toux, le diabète et la dengue. Ce sont les sujets de santé les plus demandés.',
    de: 'Schneller Zugang zu Informationen über Fieber, Kopfschmerzen, Husten, Diabetes und Dengue. Dies sind die am häufigsten gefragten Gesundheitsthemen.',
    ar: 'وصول سريع للمعلومات حول الحمى والصداع والسعال والسكري وحمى الضنك. هذه هي المواضيع الصحية الأكثر طلباً.',
    zh: '快速获取有关发烧、头痛、咳嗽、糖尿病和登革热的信息。这些是最常被询问的健康话题。',
    pt: 'Acesso rápido a informações sobre febre, dor de cabeça, tosse, diabetes e dengue. Estes são os tópicos de saúde mais consultados.',
    bn: 'জ্বর, মাথাব্যথা, কাশি, ডায়াবেটিস এবং ডেঙ্গু সম্পর্কে তথ্যে দ্রুত অ্যাক্সেস। এগুলি সবচেয়ে বেশি জিজ্ঞাসিত স্বাস্থ্য বিষয়।',
    ta: 'காய்ச்சல், தலைவலி, இருமல், நீரிழிவு மற்றும் டெங்கு பற்றிய தகவல்களுக்கு விரைவான அணுகல். இவை அதிகம் கேட்கப்படும் சுகாதார தலைப்புகள்.',
  },
  tutorialChatInputTitle: {
    en: 'Ask Your Question',
    hi: 'अपना प्रश्न पूछें',
    es: 'Haz tu Pregunta',
    fr: 'Posez Votre Question',
    de: 'Stellen Sie Ihre Frage',
    ar: 'اطرح سؤالك',
    zh: '提出您的问题',
    pt: 'Faça Sua Pergunta',
    bn: 'আপনার প্রশ্ন জিজ্ঞাসা করুন',
    ta: 'உங்கள் கேள்வியைக் கேளுங்கள்',
  },
  tutorialChatInputDesc: {
    en: 'Type your health questions here. You can ask about symptoms, treatments, prevention tips, medication reminders, or when to seek medical help.',
    hi: 'यहां अपने स्वास्थ्य प्रश्न टाइप करें। आप लक्षण, उपचार, रोकथाम युक्तियाँ, दवा रिमाइंडर, या कब चिकित्सा सहायता लेनी है के बारे में पूछ सकते हैं।',
    es: 'Escribe tus preguntas de salud aquí. Puedes preguntar sobre síntomas, tratamientos, consejos de prevención, recordatorios de medicación o cuándo buscar ayuda médica.',
    fr: 'Tapez vos questions de santé ici. Vous pouvez poser des questions sur les symptômes, les traitements, les conseils de prévention, les rappels de médicaments ou quand chercher une aide médicale.',
    de: 'Geben Sie hier Ihre Gesundheitsfragen ein. Sie können nach Symptomen, Behandlungen, Präventionstipps, Medikamentenerinnerungen oder wann Sie medizinische Hilfe suchen sollten fragen.',
    ar: 'اكتب أسئلتك الصحية هنا. يمكنك السؤال عن الأعراض والعلاجات ونصائح الوقاية وتذكيرات الأدوية أو متى تطلب المساعدة الطبية.',
    zh: '在此输入您的健康问题。您可以询问症状、治疗方法、预防建议、药物提醒或何时寻求医疗帮助。',
    pt: 'Digite suas perguntas de saúde aqui. Você pode perguntar sobre sintomas, tratamentos, dicas de prevenção, lembretes de medicação ou quando procurar ajuda médica.',
    bn: 'এখানে আপনার স্বাস্থ্য প্রশ্ন টাইপ করুন। আপনি লক্ষণ, চিকিৎসা, প্রতিরোধ টিপস, ওষুধের রিমাইন্ডার, বা কখন চিকিৎসা সাহায্য নেবেন সে বিষয়ে জিজ্ঞাসা করতে পারেন।',
    ta: 'உங்கள் சுகாதார கேள்விகளை இங்கே தட்டச்சு செய்யவும். அறிகுறிகள், சிகிச்சைகள், தடுப்பு குறிப்புகள், மருந்து நினைவூட்டல்கள் அல்லது மருத்துவ உதவி எப்போது பெற வேண்டும் என்று கேட்கலாம்.',
  },
  tutorialChatInputHint: {
    en: 'Try typing a question!',
    hi: 'एक प्रश्न टाइप करके देखें!',
    es: '¡Intenta escribir una pregunta!',
    fr: 'Essayez de taper une question!',
    de: 'Versuchen Sie, eine Frage einzugeben!',
    ar: 'جرب كتابة سؤال!',
    zh: '尝试输入一个问题！',
    pt: 'Tente digitar uma pergunta!',
    bn: 'একটি প্রশ্ন টাইপ করে দেখুন!',
    ta: 'ஒரு கேள்வியை தட்டச்சு செய்து பாருங்கள்!',
  },
  tutorialVoiceTitle: {
    en: 'Voice Input',
    hi: 'वॉयस इनपुट',
    es: 'Entrada de Voz',
    fr: 'Saisie Vocale',
    de: 'Spracheingabe',
    ar: 'الإدخال الصوتي',
    zh: '语音输入',
    pt: 'Entrada de Voz',
    bn: 'ভয়েস ইনপুট',
    ta: 'குரல் உள்ளீடு',
  },
  tutorialVoiceDesc: {
    en: 'Click the microphone to speak your question. Voice recognition works in your selected language, making it easy to communicate naturally.',
    hi: 'अपना प्रश्न बोलने के लिए माइक्रोफोन पर क्लिक करें। वॉयस रिकग्निशन आपकी चयनित भाषा में काम करता है, जिससे स्वाभाविक रूप से संवाद करना आसान हो जाता है।',
    es: 'Haz clic en el micrófono para hablar tu pregunta. El reconocimiento de voz funciona en tu idioma seleccionado, facilitando la comunicación natural.',
    fr: 'Cliquez sur le microphone pour poser votre question. La reconnaissance vocale fonctionne dans la langue sélectionnée, facilitant une communication naturelle.',
    de: 'Klicken Sie auf das Mikrofon, um Ihre Frage zu sprechen. Die Spracherkennung funktioniert in Ihrer ausgewählten Sprache und erleichtert die natürliche Kommunikation.',
    ar: 'انقر على الميكروفون للتحدث بسؤالك. يعمل التعرف على الصوت بلغتك المختارة، مما يسهل التواصل الطبيعي.',
    zh: '点击麦克风说出您的问题。语音识别支持您选择的语言，让沟通更加自然。',
    pt: 'Clique no microfone para falar sua pergunta. O reconhecimento de voz funciona no idioma selecionado, facilitando a comunicação natural.',
    bn: 'আপনার প্রশ্ন বলতে মাইক্রোফোনে ক্লিক করুন। ভয়েস রিকগনিশন আপনার নির্বাচিত ভাষায় কাজ করে, স্বাভাবিকভাবে যোগাযোগ করা সহজ করে।',
    ta: 'உங்கள் கேள்வியைப் பேச மைக்ரோஃபோனைக் கிளிக் செய்யவும். குரல் அடையாளம் உங்கள் தேர்ந்தெடுக்கப்பட்ட மொழியில் செயல்படுகிறது, இயற்கையாக தொடர்பு கொள்வதை எளிதாக்குகிறது.',
  },
  tutorialExamplesTitle: {
    en: 'Example Questions',
    hi: 'उदाहरण प्रश्न',
    es: 'Preguntas de Ejemplo',
    fr: 'Questions Exemples',
    de: 'Beispielfragen',
    ar: 'أسئلة نموذجية',
    zh: '示例问题',
    pt: 'Perguntas de Exemplo',
    bn: 'উদাহরণ প্রশ্ন',
    ta: 'எடுத்துக்காட்டு கேள்விகள்',
  },
  tutorialExamplesDesc: {
    en: 'Not sure what to ask? Click any of these example questions to get started. They cover common health topics like symptoms, prevention, and treatment.',
    hi: 'क्या पूछना है इसके बारे में सुनिश्चित नहीं हैं? शुरू करने के लिए इनमें से किसी भी उदाहरण प्रश्न पर क्लिक करें। वे लक्षण, रोकथाम और उपचार जैसे सामान्य स्वास्थ्य विषयों को कवर करते हैं।',
    es: '¿No estás seguro de qué preguntar? Haz clic en cualquiera de estas preguntas de ejemplo para comenzar. Cubren temas de salud comunes como síntomas, prevención y tratamiento.',
    fr: 'Vous ne savez pas quoi demander? Cliquez sur l\'une de ces questions exemples pour commencer. Elles couvrent des sujets de santé courants comme les symptômes, la prévention et le traitement.',
    de: 'Sie wissen nicht, was Sie fragen sollen? Klicken Sie auf eine dieser Beispielfragen, um zu beginnen. Sie decken häufige Gesundheitsthemen wie Symptome, Prävention und Behandlung ab.',
    ar: 'لست متأكداً ماذا تسأل؟ انقر على أي من هذه الأسئلة النموذجية للبدء. تغطي مواضيع صحية شائعة مثل الأعراض والوقاية والعلاج.',
    zh: '不知道问什么？点击任何示例问题开始。它们涵盖了症状、预防和治疗等常见健康话题。',
    pt: 'Não tem certeza do que perguntar? Clique em qualquer uma destas perguntas de exemplo para começar. Elas cobrem tópicos de saúde comuns como sintomas, prevenção e tratamento.',
    bn: 'কী জিজ্ঞাসা করবেন সে বিষয়ে নিশ্চিত নন? শুরু করতে এই উদাহরণ প্রশ্নগুলির যেকোনোটিতে ক্লিক করুন। তারা লক্ষণ, প্রতিরোধ এবং চিকিৎসার মতো সাধারণ স্বাস্থ্য বিষয়গুলি কভার করে।',
    ta: 'என்ன கேட்பது என்று தெரியவில்லையா? தொடங்க இந்த எடுத்துக்காட்டு கேள்விகளில் ஏதேனும் ஒன்றைக் கிளிக் செய்யவும். அவை அறிகுறிகள், தடுப்பு மற்றும் சிகிச்சை போன்ற பொதுவான சுகாதார தலைப்புகளை உள்ளடக்கியது.',
  },
  tutorialExamplesHint: {
    en: 'Click an example to start chatting',
    hi: 'चैट शुरू करने के लिए एक उदाहरण पर क्लिक करें',
    es: 'Haz clic en un ejemplo para comenzar a chatear',
    fr: 'Cliquez sur un exemple pour commencer à discuter',
    de: 'Klicken Sie auf ein Beispiel, um mit dem Chatten zu beginnen',
    ar: 'انقر على مثال لبدء الدردشة',
    zh: '点击示例开始聊天',
    pt: 'Clique em um exemplo para começar a conversar',
    bn: 'চ্যাট শুরু করতে একটি উদাহরণে ক্লিক করুন',
    ta: 'அரட்டை தொடங்க ஒரு எடுத்துக்காட்டைக் கிளிக் செய்யவும்',
  },
  tutorialStep: {
    en: 'Step',
    hi: 'चरण',
    es: 'Paso',
    fr: 'Étape',
    de: 'Schritt',
    ar: 'خطوة',
    zh: '步骤',
    pt: 'Passo',
    bn: 'ধাপ',
    ta: 'படி',
  },
  tutorialSkip: {
    en: 'Skip',
    hi: 'छोड़ें',
    es: 'Saltar',
    fr: 'Passer',
    de: 'Überspringen',
    ar: 'تخطي',
    zh: '跳过',
    pt: 'Pular',
    bn: 'এড়িয়ে যান',
    ta: 'தவிர்',
  },
  tutorialPrev: {
    en: 'Back',
    hi: 'पीछे',
    es: 'Atrás',
    fr: 'Retour',
    de: 'Zurück',
    ar: 'السابق',
    zh: '返回',
    pt: 'Voltar',
    bn: 'পিছনে',
    ta: 'பின்',
  },
  tutorialNext: {
    en: 'Next',
    hi: 'अगला',
    es: 'Siguiente',
    fr: 'Suivant',
    de: 'Weiter',
    ar: 'التالي',
    zh: '下一步',
    pt: 'Próximo',
    bn: 'পরবর্তী',
    ta: 'அடுத்து',
  },
  tutorialFinish: {
    en: 'Get Started',
    hi: 'शुरू करें',
    es: 'Comenzar',
    fr: 'Commencer',
    de: 'Loslegen',
    ar: 'ابدأ',
    zh: '开始使用',
    pt: 'Começar',
    bn: 'শুরু করুন',
    ta: 'தொடங்கு',
  },
  tutorialRestart: {
    en: 'Restart Tutorial',
    hi: 'ट्यूटोरियल पुनः आरंभ करें',
    es: 'Reiniciar Tutorial',
    fr: 'Recommencer le Tutoriel',
    de: 'Tutorial neu starten',
    ar: 'إعادة بدء الدرس',
    zh: '重新开始教程',
    pt: 'Reiniciar Tutorial',
    bn: 'টিউটোরিয়াল পুনরায় শুরু করুন',
    ta: 'பயிற்சியை மீண்டும் தொடங்கு',
  },
};

// Helper to get questions in the selected language
export const getQuickQuestions = (language: Language) => ({
  symptoms: {
    en: 'What are common symptoms I should watch out for?',
    hi: 'मुझे किन सामान्य लक्षणों पर ध्यान देना चाहिए?',
    es: '¿Cuáles son los síntomas comunes que debo tener en cuenta?',
    fr: 'Quels sont les symptômes courants auxquels je dois faire attention?',
    de: 'Auf welche häufigen Symptome sollte ich achten?',
    ar: 'ما هي الأعراض الشائعة التي يجب أن أنتبه لها؟',
    zh: '我应该注意哪些常见症状？',
    pt: 'Quais são os sintomas comuns que devo observar?',
    bn: 'কোন সাধারণ লক্ষণগুলি আমার লক্ষ্য রাখা উচিত?',
    ta: 'நான் கவனிக்க வேண்டிய பொதுவான அறிகுறிகள் என்ன?',
  }[language],
  prevention: {
    en: 'How can I prevent common illnesses?',
    hi: 'मैं सामान्य बीमारियों को कैसे रोक सकता हूं?',
    es: '¿Cómo puedo prevenir enfermedades comunes?',
    fr: 'Comment puis-je prévenir les maladies courantes?',
    de: 'Wie kann ich häufige Krankheiten vorbeugen?',
    ar: 'كيف يمكنني الوقاية من الأمراض الشائعة؟',
    zh: '我如何预防常见疾病？',
    pt: 'Como posso prevenir doenças comuns?',
    bn: 'আমি কীভাবে সাধারণ রোগ প্রতিরোধ করতে পারি?',
    ta: 'பொதுவான நோய்களை எப்படி தடுக்கலாம்?',
  }[language],
  firstAid: {
    en: 'What are basic first aid tips?',
    hi: 'बुनियादी प्राथमिक चिकित्सा युक्तियाँ क्या हैं?',
    es: '¿Cuáles son los consejos básicos de primeros auxilios?',
    fr: 'Quels sont les conseils de base en premiers secours?',
    de: 'Was sind grundlegende Erste-Hilfe-Tipps?',
    ar: 'ما هي نصائح الإسعافات الأولية الأساسية؟',
    zh: '基本急救技巧是什么？',
    pt: 'Quais são as dicas básicas de primeiros socorros?',
    bn: 'প্রাথমিক চিকিৎসার মৌলিক টিপস কী?',
    ta: 'அடிப்படை முதலுதவி குறிப்புகள் என்ன?',
  }[language],
  whenToSeeDoctor: {
    en: 'When should I see a doctor?',
    hi: 'मुझे डॉक्टर से कब मिलना चाहिए?',
    es: '¿Cuándo debo ver a un médico?',
    fr: 'Quand devrais-je consulter un médecin?',
    de: 'Wann sollte ich einen Arzt aufsuchen?',
    ar: 'متى يجب أن أزور الطبيب؟',
    zh: '我什么时候应该看医生？',
    pt: 'Quando devo consultar um médico?',
    bn: 'কখন আমার ডাক্তার দেখানো উচিত?',
    ta: 'எப்போது மருத்துவரை பார்க்க வேண்டும்?',
  }[language],
  fever: {
    en: 'What should I do for a fever?',
    hi: 'बुखार होने पर मुझे क्या करना चाहिए?',
    es: '¿Qué debo hacer si tengo fiebre?',
    fr: 'Que dois-je faire en cas de fièvre?',
    de: 'Was soll ich bei Fieber tun?',
    ar: 'ماذا يجب أن أفعل في حالة الحمى؟',
    zh: '发烧时我应该怎么办？',
    pt: 'O que devo fazer se tiver febre?',
    bn: 'জ্বর হলে কী করা উচিত?',
    ta: 'காய்ச்சல் வந்தால் என்ன செய்ய வேண்டும்?',
  }[language],
  headache: {
    en: 'What causes headaches and how to relieve them?',
    hi: 'सिरदर्द का कारण क्या है और इसे कैसे कम करें?',
    es: '¿Qué causa los dolores de cabeza y cómo aliviarlos?',
    fr: 'Quelles sont les causes des maux de tête et comment les soulager?',
    de: 'Was verursacht Kopfschmerzen und wie kann man sie lindern?',
    ar: 'ما الذي يسبب الصداع وكيفية تخفيفه؟',
    zh: '什么导致头痛以及如何缓解？',
    pt: 'O que causa dores de cabeça e como aliviá-las?',
    bn: 'মাথাব্যথার কারণ কী এবং কীভাবে উপশম করা যায়?',
    ta: 'தலைவலி எதனால் வருகிறது மற்றும் எப்படி நிவாரணம் பெறுவது?',
  }[language],
  cough: {
    en: 'How do I treat a cough and cold at home?',
    hi: 'घर पर खांसी और जुकाम का इलाज कैसे करें?',
    es: '¿Cómo puedo tratar la tos y el resfriado en casa?',
    fr: 'Comment traiter la toux et le rhume à la maison?',
    de: 'Wie behandle ich Husten und Erkältung zu Hause?',
    ar: 'كيف أعالج السعال والبرد في المنزل؟',
    zh: '如何在家治疗咳嗽和感冒？',
    pt: 'Como posso tratar tosse e resfriado em casa?',
    bn: 'বাড়িতে কাশি এবং সর্দি কীভাবে চিকিৎসা করব?',
    ta: 'வீட்டில் இருமல் மற்றும் சளியை எப்படி சிகிச்சை செய்வது?',
  }[language],
  diabetes: {
    en: 'How can I prevent diabetes?',
    hi: 'मैं मधुमेह को कैसे रोक सकता हूं?',
    es: '¿Cómo puedo prevenir la diabetes?',
    fr: 'Comment puis-je prévenir le diabète?',
    de: 'Wie kann ich Diabetes vorbeugen?',
    ar: 'كيف يمكنني الوقاية من السكري؟',
    zh: '我如何预防糖尿病？',
    pt: 'Como posso prevenir a diabetes?',
    bn: 'আমি কীভাবে ডায়াবেটিস প্রতিরোধ করতে পারি?',
    ta: 'நீரிழிவை எப்படி தடுக்கலாம்?',
  }[language],
  dengue: {
    en: 'What are the symptoms of dengue?',
    hi: 'डेंगू के लक्षण क्या हैं?',
    es: '¿Cuáles son los síntomas del dengue?',
    fr: 'Quels sont les symptômes de la dengue?',
    de: 'Was sind die Symptome von Dengue?',
    ar: 'ما هي أعراض حمى الضنك؟',
    zh: '登革热的症状是什么？',
    pt: 'Quais são os sintomas da dengue?',
    bn: 'ডেঙ্গুর লক্ষণ কী?',
    ta: 'டெங்குவின் அறிகுறிகள் என்ன?',
  }[language],
});

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('medical-chatbot-language');
    return (saved as Language) || 'en';
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('medical-chatbot-language', lang);
  }, []);

  const t = useCallback((key: string): string => {
    const translation = translations[key];
    if (!translation) return key;
    return translation[language] || translation.en || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
